services:
  postgres:
    container_name: postgres-regulus
    image: 'postgis/postgis:17-3.5-alpine'
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - regulus
  mailhog:
    container_name: mailing_regulus
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - regulus

  flyway:
    container_name: flyway-regulus
    image: flyway/flyway
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres-regulus:5432/${DATABASE}
      FLYWAY_USER: ${DB_USERNAME}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - regulus
    depends_on:
      - postgres
    command: [ "migrate"]

networks:
  regulus:
