spring:
  docker:
    compose:
      stop:
        command: down
  application:
    name: regulus
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DATABASE}?stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
#    security:
#      oauth2:
#        resourceserver:
#          jwt:
#            issuer-uri: https://accounts.google.com
#            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

regulus:
  providers:
    gis:
      name: 'GisProvider'
      api-key: ${GIS_API_KEY}
      base-url: https://api.tomtom.com
#server:
#  ssl:
#    key-store: ${SSL_KEY_STORE}
#    key-store-password: ${SSL_KEY_STORE_PASSWORD}
#    key-store-type: pkcs12
#    key-alias: aeflheim
#    key-password: ${SSL_KEY_PASSWORD}
#  port: 8443

