spring:
  docker:
    compose:
      stop:
        command: down
  application:
    name: regulus
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DATABASE}?stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

regulus:
  providers:
    gis:
      name: 'GISProvider'
      api-key: ${GIS_API_KEY}
      base-url: ${GIS_API_BASE_URL}

#server:
#  ssl:
#    key-store: ${SSL_KEY_STORE}
#    key-store-password: ${SSL_KEY_STORE_PASSWORD}
#    key-store-type: pkcs12
#    key-alias: aeflheim
#    key-password: ${SSL_KEY_PASSWORD}
#  port: 8443

